/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appproyecto.Ventas;

import appproyecto.MainV;
import javax.swing.JOptionPane;

/**
 *
 * @author FuryCoder
 */
public class OrdenPedidoV extends javax.swing.JPanel {

    /**
     * Creates new form OrdenPedido
     */
    public OrdenPedidoV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        clientCodeF = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lugarEntregaF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        despachoOption = new javax.swing.JRadioButton();
        mostradorOption = new javax.swing.JRadioButton();
        jCheckBox1 = new javax.swing.JCheckBox();
        doB = new javax.swing.JButton();
        guiaB = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        cancelB = new javax.swing.JButton();

        clientCodeF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientCodeFActionPerformed(evt);
            }
        });

        jLabel1.setText("Codigo Cliente");

        jLabel2.setText("Lugar Entrega");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Efectivo", "Tarjeta Debito", "Tarjeta Credito", "Credito" }));

        jLabel3.setText("Condicion de Pago");

        buttonGroup1.add(despachoOption);
        despachoOption.setText("Despacho");
        despachoOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despachoOptionActionPerformed(evt);
            }
        });

        buttonGroup1.add(mostradorOption);
        mostradorOption.setText("Mostrador");
        mostradorOption.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostradorOptionActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Parcial");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });

        doB.setText("Documento");
        doB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                doBActionPerformed(evt);
            }
        });

        guiaB.setText("Guia Remision");
        guiaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guiaBActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "CODIGO", "PRODUCTO", "CANTIDAD", "PRECIO", "SUBTOTAL"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Short.class, java.lang.Short.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(jTable1);

        cancelB.setText("Cancelar");
        cancelB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(cancelB)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(clientCodeF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1))
                            .addGap(53, 53, 53)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lugarEntregaF, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(despachoOption)
                                    .addGap(18, 18, 18)
                                    .addComponent(jCheckBox1))
                                .addComponent(mostradorOption))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(guiaB, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addComponent(doB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(52, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(despachoOption)
                    .addComponent(jCheckBox1)
                    .addComponent(guiaB))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(clientCodeF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lugarEntregaF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(mostradorOption))
                    .addComponent(doB, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(cancelB)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientCodeFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientCodeFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clientCodeFActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void mostradorOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostradorOptionActionPerformed
        if(mostradorOption.isEnabled()){
            jCheckBox1.setEnabled(false);
        }
    }//GEN-LAST:event_mostradorOptionActionPerformed

    private void despachoOptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despachoOptionActionPerformed
        if(despachoOption.isEnabled()){
            jCheckBox1.setEnabled(true);
        }
    }//GEN-LAST:event_despachoOptionActionPerformed

    private void cancelBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBActionPerformed
        MainV.SETPANEL(new mainVentas());
    }//GEN-LAST:event_cancelBActionPerformed

    private void guiaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guiaBActionPerformed
        if(buttonGroup1.getSelection()==null || clientCodeF.getText().equals("") || lugarEntregaF.getText().equals("")|| jComboBox1.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "El formulario no esta completo" , "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_guiaBActionPerformed

    private void doBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_doBActionPerformed
        if(buttonGroup1.getSelection()==null || clientCodeF.getText().equals("") || lugarEntregaF.getText().equals("")|| jComboBox1.getSelectedItem()==null){
            JOptionPane.showMessageDialog(this, "El formulario no esta completo" , "ERROR",JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_doBActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancelB;
    private javax.swing.JTextField clientCodeF;
    private javax.swing.JRadioButton despachoOption;
    private javax.swing.JButton doB;
    private javax.swing.JButton guiaB;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField lugarEntregaF;
    private javax.swing.JRadioButton mostradorOption;
    // End of variables declaration//GEN-END:variables
}
