/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appproyecto.Compras;

import Login.Login;
import Login.SQLConnections;
import appproyecto.MainMenu;
import appproyecto.MainV;
import java.awt.BorderLayout;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JScrollPane;
import javax.swing.JTable;

/**
 *
 * @author alejandro
 */
public class mainCompras extends javax.swing.JPanel {

    /**
     * Creates new form mainCompras
     */
    public mainCompras() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bProveedores = new javax.swing.JButton();
        bProductos = new javax.swing.JButton();
        bDocumentos = new javax.swing.JButton();
        bRegreso = new javax.swing.JButton();
        bOrdenC = new javax.swing.JButton();
        bRegCompras = new javax.swing.JButton();
        bCtaCte = new javax.swing.JButton();
        bEstadisticas = new javax.swing.JButton();
        panelTableContainer = new javax.swing.JPanel();

        bProveedores.setText("Proveedores");
        bProveedores.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bProveedoresMousePressed(evt);
            }
        });

        bProductos.setText("Productos");
        bProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bProductosMousePressed(evt);
            }
        });

        bDocumentos.setText("Documentos");
        bDocumentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bDocumentosActionPerformed(evt);
            }
        });

        bRegreso.setText("Regresar");
        bRegreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bRegresoMousePressed(evt);
            }
        });

        bOrdenC.setText("Orden de compras");
        bOrdenC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bOrdenCMousePressed(evt);
            }
        });
        bOrdenC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bOrdenCActionPerformed(evt);
            }
        });

        bRegCompras.setText("Ver Registro de compras");
        bRegCompras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegComprasActionPerformed(evt);
            }
        });

        bCtaCte.setText("Ver Cuenta Corriente");
        bCtaCte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bCtaCteActionPerformed(evt);
            }
        });

        bEstadisticas.setText("Estadisticas");
        bEstadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bEstadisticasActionPerformed(evt);
            }
        });

        panelTableContainer.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(bProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(bEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bRegCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(bCtaCte, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(184, 184, 184)
                                .addComponent(bRegreso))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(bOrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(bDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bOrdenC, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bDocumentos, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84)
                .addComponent(panelTableContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 248, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bRegreso)
                    .addComponent(bEstadisticas, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bRegCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bCtaCte, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bRegresoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bRegresoMousePressed
        MainV.SETPANEL(new MainMenu());
    }//GEN-LAST:event_bRegresoMousePressed

    private void bProveedoresMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProveedoresMousePressed
        MainV.SETPANEL(new RegistrarProveedor());
    }//GEN-LAST:event_bProveedoresMousePressed

    private void bProductosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bProductosMousePressed
        MainV.SETPANEL(new ProductoLV());
    }//GEN-LAST:event_bProductosMousePressed

    private void bOrdenCMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bOrdenCMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_bOrdenCMousePressed

    private void bOrdenCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bOrdenCActionPerformed
        MainV.SETPANEL(new OrdenComprasV());
    }//GEN-LAST:event_bOrdenCActionPerformed

    private void bDocumentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bDocumentosActionPerformed
        MainV.SETPANEL(new DocumentosV());
    }//GEN-LAST:event_bDocumentosActionPerformed

    private void bRegComprasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegComprasActionPerformed
        Login logi = new Login();
        SQLConnections log = new SQLConnections();
        Connection con = log.SQLConnection();
        PreparedStatement ps;
        ResultSet rs;
        JTable table;
        try{
        ps = con.prepareStatement("SELECT * FROM DOC_COMPRAS");
        rs = ps.executeQuery();
        table = new JTable(logi.buildTableModel(rs));
        JScrollPane scrollPane = new JScrollPane(table);
        panelTableContainer.add(scrollPane,BorderLayout.CENTER);
        panelTableContainer.repaint();
        panelTableContainer.revalidate();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bRegComprasActionPerformed

    private void bCtaCteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bCtaCteActionPerformed
        Login logi = new Login();
        SQLConnections log = new SQLConnections();
        Connection con = log.SQLConnection();
        PreparedStatement ps;
        ResultSet rs;
        JTable table;
        try{
        ps = con.prepareStatement("SELECT * FROM VER_CC_PROVEEDOR");
        rs = ps.executeQuery();
        table = new JTable(logi.buildTableModel(rs));
        JScrollPane scrollPane = new JScrollPane(table);
        panelTableContainer.add(scrollPane,BorderLayout.CENTER);
        panelTableContainer.repaint();
        panelTableContainer.revalidate();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bCtaCteActionPerformed

    private void bEstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bEstadisticasActionPerformed
        Login logi = new Login();
        SQLConnections log = new SQLConnections();
        Connection con = log.SQLConnection();
        PreparedStatement ps;
        ResultSet rs;
        JTable table;
        try{
        ps = con.prepareStatement("SELECT * FROM COMPRAS_PRODUCTOS");
        rs = ps.executeQuery();
        table = new JTable(logi.buildTableModel(rs));
        JScrollPane scrollPane = new JScrollPane(table);
        panelTableContainer.add(scrollPane,BorderLayout.CENTER);
        panelTableContainer.repaint();
        panelTableContainer.revalidate();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_bEstadisticasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bCtaCte;
    private javax.swing.JButton bDocumentos;
    private javax.swing.JButton bEstadisticas;
    private javax.swing.JButton bOrdenC;
    private javax.swing.JButton bProductos;
    private javax.swing.JButton bProveedores;
    private javax.swing.JButton bRegCompras;
    private javax.swing.JButton bRegreso;
    private javax.swing.JPanel panelTableContainer;
    // End of variables declaration//GEN-END:variables
}
