/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appproyecto.Compras;

import appproyecto.MainV;

/**
 *
 * @author alejandro
 */
public class ProductosV extends javax.swing.JPanel {

    /**
     * Creates new form Productos
     */
    public ProductosV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bRegreso = new javax.swing.JButton();
        bProductoL = new javax.swing.JButton();
        bProductoA = new javax.swing.JButton();

        bRegreso.setText("Regreso");
        bRegreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRegresoActionPerformed(evt);
            }
        });

        bProductoL.setText("Producto Local");
        bProductoL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoLActionPerformed(evt);
            }
        });

        bProductoA.setText("Producto almacenado");
        bProductoA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bProductoAActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(293, Short.MAX_VALUE)
                .addComponent(bRegreso)
                .addGap(34, 34, 34))
            .addGroup(layout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bProductoA, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                    .addComponent(bProductoL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addComponent(bProductoL, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(bProductoA, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(bRegreso)
                .addGap(40, 40, 40))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void bRegresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRegresoActionPerformed
        MainV.SETPANEL(new mainCompras());
    }//GEN-LAST:event_bRegresoActionPerformed

    private void bProductoLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoLActionPerformed
        MainV.SETPANEL(new ProductoLV());
    }//GEN-LAST:event_bProductoLActionPerformed

    private void bProductoAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bProductoAActionPerformed
        MainV.SETPANEL(new ProductoAV());
    }//GEN-LAST:event_bProductoAActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bProductoA;
    private javax.swing.JButton bProductoL;
    private javax.swing.JButton bRegreso;
    // End of variables declaration//GEN-END:variables
}
