/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package appproyecto;

import Login.Login;
import appproyecto.Compras.mainCompras;

/**
 *
 * @author alejandro
 */
public class MainMenu extends javax.swing.JPanel {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bCompras = new javax.swing.JButton();
        bAlmacen = new javax.swing.JButton();
        bVentas = new javax.swing.JButton();
        bLogout = new javax.swing.JButton();
        lWelcome = new javax.swing.JLabel();

        bCompras.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bCompras.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/compras_icon.png"))); // NOI18N
        bCompras.setText("Compras");
        bCompras.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                bComprasMousePressed(evt);
            }
        });

        bAlmacen.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bAlmacen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/almacen_icon.png"))); // NOI18N
        bAlmacen.setText("Almacen");

        bVentas.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        bVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/ventas_icon.png"))); // NOI18N
        bVentas.setText("Ventas");

        bLogout.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/logout_icon.png"))); // NOI18N
        bLogout.setText("Cerrar Sesion");
        bLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLogoutActionPerformed(evt);
            }
        });

        lWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lWelcome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(bCompras)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(bLogout))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(bAlmacen)
                                .addGap(18, 18, 18)
                                .addComponent(bVentas))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(lWelcome)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(lWelcome)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bCompras, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bAlmacen, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bVentas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addComponent(bLogout)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lWelcome.setText("Bienvenido "+Login.USER_LOGGED.user);
    }// </editor-fold>//GEN-END:initComponents

    private void bComprasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bComprasMousePressed
        MainV.SETPANEL(new mainCompras());
    }//GEN-LAST:event_bComprasMousePressed

    private void bLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLogoutActionPerformed
        MainV.SETPANEL(new LoginV());
    }//GEN-LAST:event_bLogoutActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAlmacen;
    private javax.swing.JButton bCompras;
    private javax.swing.JButton bLogout;
    private javax.swing.JButton bVentas;
    private javax.swing.JLabel lWelcome;
    // End of variables declaration//GEN-END:variables
}
